config/routes.rb
Roflmail::Application.routes.draw do
  resources :accounts do
    member do
      get 'fetch'
      get 'mailboxes'
    end
  end

  get "main/index"

  devise_for :users

  root :to => "main#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  belongs_to :sender
  belongs_to :retriever

  accepts_nested_attributes_for :sender
  accepts_nested_attributes_for :retriever
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :account
  validates_presence_of :account_id, :message_id, :data
end

app/models/retriever.rb
class Retriever < Transporter
  MODUS_CHOICES = [['IMAP', 'imap'], ['POP3', 'pop3']]

  def find(*args, &block)
    mail.find(*args, &block)
  end

  def last(*args, &block)
    mail.last(*args, &block)
  end

  def first(*args, &block)
    mail.first(*args, &block)
  end

  def mailboxes(parent = nil)
    case modus
    when 'imap'
      mailboxes = []
      mail.connection { |imap| mailboxes = imap.list("", parent ? "#{parent}/%" : "%") }
      mailboxes
    end
  end

  private
    def mail
      if @mail.nil?
        klass =
          case modus
          when 'imap' then Mail::IMAP
          end
        @mail = klass.new({
          :address => address, :port => port,
          :user_name => user_name, :password => password,
          :enable_ssl => enable_ssl
        })
      end
      @mail
    end
end

app/models/sender.rb
class Sender < Transporter
  MODUS_CHOICES = [['SMTP', 'smtp']]
  AUTHENTICATION_CHOICES = [['Plain', 'plain']]
end

app/models/transporter.rb
class Transporter < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :password, :password_confirmation, :remember_me

  validates_presence_of :username
  validates_uniqueness_of :username, :case_sensitive => false, :allow_blank => true

  validates_uniqueness_of :email, :case_sensitive => false, :allow_blank => true
  validates_format_of     :email, :with => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i, :allow_blank => true

  with_options :if => :password_required? do |v|
    v.validates_presence_of     :password
    v.validates_confirmation_of :password
    v.validates_length_of       :password, :within => 6..20, :allow_blank => true
  end

  has_many :accounts

  protected

    # Checks whether a password is needed or not. For validations only.
    # Passwords are always required if it's a new record, or if the password
    # or confirmation are being set somewhere.
    def password_required?
      !persisted? || !password.nil? || !password_confirmation.nil?
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!

  # GET /accounts
  # GET /accounts.xml
  def index
    @accounts = current_user.accounts

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.xml
  def show
    @account = current_user.accounts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
    end
  end

  def fetch
    @account = current_user.accounts.find(params[:id])
    options = {:count => 10, :order => :desc}
    options[:mailbox] = params[:mailbox]  if params[:mailbox]
    @mail = @account.retriever.last(options)
    render :partial => 'mail'
  end

  def mailboxes
    @account = current_user.accounts.find(params[:id])
    @mailboxes = @account.retriever.mailboxes(params[:mailbox])
    render :partial => 'mailboxes'
  end

  # GET /accounts/new
  # GET /accounts/new.xml
  def new
    @account = current_user.accounts.build
    @account.build_retriever
    @account.build_sender

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = current_user.accounts.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.xml
  def create
    @account = current_user.accounts.build(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => 'Account was successfully created.') }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def update
    @account = current_user.accounts.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Account was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.xml
  def destroy
    @account = current_user.accounts.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(accounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
  def mailbox_tag(name)
    current = params[:mailbox] || "INBOX"
    content_tag(:li, name, :class => (current == name ? 'mailbox current' : 'mailbox'))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <fieldset>
    <legend>Retrieiving</legend>
    <%= f.fields_for :retriever do |f| %>
      <div class="field">
        <%= f.label :modus, "Method" %><br />
        <%= f.select :modus, Retriever::MODUS_CHOICES %>
      </div>
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_field :address %>
      </div>
      <div class="field">
        <%= f.label :port %><br />
        <%= f.text_field :port %>
      </div>
      <div class="field">
        <%= f.label :user_name %><br />
        <%= f.text_field :user_name %>
      </div>
      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :enable_ssl, "Enable SSL?" %>
        <%= f.check_box :enable_ssl %>
      </div>
    <%- end -%>
  </fieldset>

  <fieldset>
    <legend>Sending</legend>
    <%= f.fields_for :sender do |f| %>
      <div class="field">
        <%= f.label :modus, "Method" %><br />
        <%= f.select :modus, Sender::MODUS_CHOICES %>
      </div>
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_field :address %>
      </div>
      <div class="field">
        <%= f.label :port %><br />
        <%= f.text_field :port %>
      </div>
      <div class="field">
        <%= f.label :user_name %><br />
        <%= f.text_field :user_name %>
      </div>
      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :authentication %><br />
        <%= f.select :authentication, Sender::AUTHENTICATION_CHOICES %>
      </div>
      <div class="field">
        <%= f.label :enable_starttls_auto, "Enable STARTTLS?" %>
        <%= f.check_box :enable_starttls_auto %>
      </div>
    <%- end -%>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_mail.html.erb
<table>
  <thead>
    <tr>
      <th>From</th>
      <th>Subject</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <%- @mail.each do |message| -%>
      <tr>
        <td><%= message['From'] %></td>
        <td><%= message.subject %></td>
        <td><%= message.date %></td>
      </tr>
    <%- end -%>
  </tbody>
</table>

app/views/accounts/_mailboxes.html.erb
<%- if !@mailboxes.empty? -%>
<ul>
  <%- @mailboxes.each do |mailbox| -%>
    <%= mailbox_tag(mailbox.name) %>
  <%- end -%>
</ul>
<%- end -%>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Retriever</th>
    <th>Sender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= account.retriever_id %></td>
    <td><%= account.sender_id %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

<div id="mailboxes">Loading...</div>
<div id="mail">Loading...</div>

<script type="text/javascript">
  $(function() {
    $('#mailboxes').load("<%= mailboxes_account_path(@account) %>");
    $('#mail').load("<%= fetch_account_path(@account) %>");
    $('li.mailbox:not(.current)').live('click', function() {
      var self = $(this);
      self.siblings('.current').removeClass('current');
      self.addClass('current');

      $('#mail').html('Loading...');
      $.ajax({
        url: '<%= fetch_account_path(@account) %>',
        data: {mailbox: self.html()},
        success: function(data, status, xhr) {
          $('#mail').html(data);
        },
        dataType: 'html'
      });
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roflmail</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>